### PR TITLE
Improve clean method from Makefile

### PR DESCRIPTION
**Pull request by edgardleal**
The make task was traing to remove .exe file and thats file
don't exists.
  Now the task is remove compiled programs to.

### CODE REVIEW

**Comment by codeplea** [comment]
Hi and thanks for your contribution.

There are a couple issues that would need to be resolved before I merge it.

1) I don't want the `-ansi` flag added. It keeps the compiler from performing many optimizations, and usually results in slower binaries.

2) The `rm *.exe` is there because I'm developing on Windows where gcc adds ".exe" to executable automatically. I'm not sure about the best way to make it cross-platform. Maybe `rm -f *.exe` followed by `rm -f example1`, etc. The `-f` flag should keep rm from having an error when the files don't exist.

**Comment by edgardleal** [comment]
Ok. I'll solve these issues and resubmit. Thanks for feedback.

**Comment by codeplea** [comment]
Where did you get the idea for the `rm xxx || echo` syntax? I get what you're doing, but isn't the standard way to use `rm -f xxx`?

**Comment by edgardleal** [comment]
I make this to avoid exit with error code when the files don't exists. Some integration apps like Jenkins consider a build failed when exist code is different of 0 ( Zero ) .

**Comment by edgardleal** [comment]
I don't know if this changes are relevant for project. If don't, do not worry about rejecting the pull. I will study your code more deeply and if a find anything to help I will create other pull request.

**Comment by codeplea** [comment]
> Some integration apps like Jenkins consider a build failed when exist code is different of 0 ( Zero ) .

Yes. That's the purpose of the `-f` flag in `rm -f file_name_here`. The `-f` flag will make `rm` always return 0, even if the file does not exists.

The `rm xxx || echo` usage is weird, because you are using echo for something other than its intended purpose. If you really want it that way, you should do `rm xxx || true` or `rm xxx || :` instead of `echo`. But again, I think that `rm -f` is the proper way, unless I have missed something.

**Comment by edgardleal** [comment]
I agree.

**Pull request closed without merging**
