### PR TITLE
ANSI C compatibility fixes: declarations must always preceed statements

### PR DESCRIPTION
**Pull request by mateuszviste**
genann states to be ANSI C compatible, but clang disagrees when executed with -std=gnu89:
````
genann.c:92:12: warning: ISO C90 forbids mixing declarations and code [-Wdeclaration-after-statement]
    size_t j = (size_t)((a-sigmoid_dom_min)*interval+0.5);
           ^
genann.c:115:15: warning: ISO C90 forbids mixing declarations and code [-Wdeclaration-after-statement]
    const int hidden_weights = hidden_layers ? (inputs+1) * hidden + (hidden_layers-1) * (hidden+1) * hidden : 0;
              ^
genann.c:161:13: warning: ISO C90 forbids mixing declarations and code [-Wdeclaration-after-statement]
    genann *ann = genann_init(inputs, hidden_layers, hidden, outputs);
            ^
genann.c:220:9: warning: ISO C90 forbids mixing declarations and code [-Wdeclaration-after-statement]
    int h, j, k;
        ^
genann.c:282:9: warning: ISO C90 forbids mixing declarations and code [-Wdeclaration-after-statement]
    int h, j, k;
        ^
genann.c:399:9: warning: ISO C90 forbids mixing declarations and code [-Wdeclaration-after-statement]
    int i;
        ^
6 warnings generated.
````

this patch fixes the above.

### CODE REVIEW

**Comment by codeplea** [comment]
Thanks, but I think I will go a different direction and just update to documentation to clarify it's C99. Sorry for the confusion.

**Comment by mateuszviste** [comment]
ah, too bad... ANSI C compatibility was the main reason I was looking at it in the first place - and truly it was almost perfect already, only a few declarations needed to be moved a little bit. I guess I will keep using my patched version then, crossing fingers for no "hard" C99 dependencies getting into genann in the future. :) Awesome work btw! I'm trying to teach genann playing an eastern-European variant of Go.

**Comment by codeplea** [comment]
I don't plan to use other C99 features, but I really think the code is much cleaner when the variable declarations are near their first usage. It's just easier to read.

What platform are you on where C99 isn't available?

Also, C99 *is* an ANSI standard, if that makes you feel any better. lol

**Comment by mateuszviste** [comment]
It is actually not a platform problem, I'm using the original ANSI C (ie. 1989/1990) because of... hard to tell - personal religion? sentiment? struggle for minimalism? I simply like the fact that it is the lowest C common denominator, it is also a method for not being distracted by the fluffy features present in subsequent standards. I try to stick to C89 in all my projects.

Anyway, a possible alternative that would allow to keep declarations in the immediate vicinity of where they are used while still retaining C89 compatibility could be creating local scopes. It would require adding two extra parenthesis here and there, like so:

````
double genann_act_sigmoid_cached(const genann *ann unused, double a) {
    assert(!isnan(a));
    if (a < sigmoid_dom_min) return lookup[0];
    if (a >= sigmoid_dom_max) return lookup[LOOKUP_SIZE - 1];
    {        /* EXTRA PARENTHESIS HERE */
    size_t j = (size_t)((a-sigmoid_dom_min)*interval+0.5);

    /* Because floating point... */
    if (unlikely(j >= LOOKUP_SIZE)) return lookup[LOOKUP_SIZE - 1];

    return lookup[j];
    }      /* AND HERE */
}
````

Is it something you would find possibly acceptable?

**Pull request closed without merging**
